import "./assets/css/main.css"
import "./assets/scripts/main"
//import "./css/style.css";
import "./StorePage/filtres";
import "./StorePage/products";
import "./StorePage/storePage.css";
import "./findData";
import "./assets/data/productsData";
import "./CartPage/cartPage";
import "./pageSwitching";
import "./descriptionPage/productDescription";
import "./header";
